### ISSUE TITLE
defcon27_csharp_workshop + invoke-obfuscate

### ISSUE THREAD

**Issue by joker8989** [mvelazc0/defcon27_csharp_workshop#1]
Hey i have tested your tool in different payloads and applications and it all went pretty well.. love your work...
so i went one step forward and i used invoke-obfuscate to obfuscate my powershell payload or script... i encoded it to base64 myself (cause its not encoded its only obfuscated)
and i put it into 2.cs "string script = 'encodedblabla' and no errors were displayed while creating and running the exe but no session was created
Like u said i did not specify the "powershell -nop -w 1 -enc ......." only the "......"

wanna say i used venom to create powershell payload and it worked :) but when tried to obfuscate it no session was created :(

if i could use your help thankx you very much :)

**Comment by mvelazc0** [comment]
Thanks! hope you enjoyed the workshop.

Have you tried your obfuscated payload by itself ? ( without wrapping in C#)  ? Does that work ?

**Comment by joker8989** [comment]
@mvelazc0 Yes it does work i execute it on powershell ISE it looks like this:
powershell.exe -enc "obfuscated code" (because powershell.exe -nop -w 1 -enc need to be removed)
after all yes the obfuscated powershell payload does work :)
can u help me resolve the issue?
